version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directories:
      - /
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directories:
      - /terraform/**/*
    schedule:
      interval: weekly